# Generated by Django 4.1.5 on 2023-01-08 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('roll', models.CharField(max_length=5)),
                ('subject', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=20)),
            ],
        ),
    ]
